# Generated by Django 2.0.2 on 2018-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180311_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
