# Generated by Django 2.0.2 on 2018-03-24 11:34

import apps.board.models
from django.db import migrations, models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20180312_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage=storages.backends.ftp.FTPStorage(), upload_to=apps.board.models.update_filename),
        ),
    ]
