# Generated by Django 2.0.2 on 2018-03-08 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userpic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static'),
            preserve_default=False,
        ),
    ]
