# Generated by Django 2.0.2 on 2018-03-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profile_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userpic',
            field=models.ImageField(upload_to='img'),
        ),
    ]
